### ISSUE TITLE
多服务端配置文件里面应该怎么写？

### ISSUE THREAD

**Issue by etotakeo** [NolanHzy/nvjdc#7]
我是这样写的，但是重启容器后就循环重启
{
  ///最大支持几个网页
  "MaxTab": "4",
  //网站标题
  "Title": "京东签到获取小饼干",
  //网站公告
  "Announcement": "此工具仅限内部使用，为了您的财产安全，请关闭京东免密支付。",
  ///多青龙配置
  "Config": [
    {
      //序号必须从1开始
      "QLkey": 1,
      //服务器名称
      "QLName": "重庆电信-动态IP",
      //青龙url
      "QLurl": "http://1***6:5700",
      //青龙2,9 OpenApi Client ID
      "QL_CLIENTID": "o8***ep",
      //青龙2,9 OpenApi Client Secret
      "QL_SECRET": "Eaw***wEpY",
      //青龙面包最大ck容量
      "QL_CAPACITY": 50,
      //消息推送二维码
      "QRurl":""
    }
    {
      //序号必须从1开始
      "QLkey": 2,
      //服务器名称
      "QLName": "上海良心云-固定IP",
      //青龙url
      "QLurl": "http://1***6:5700",
      //青龙2,9 OpenApi Client ID
      "QL_CLIENTID": "o8***ep",
      //青龙2,9 OpenApi Client Secret
      "QL_SECRET": "Eaw***wEpY",
      //青龙面包最大ck容量
      "QL_CAPACITY": 50,
      //消息推送二维码
      "QRurl":""
    }
  ]
}

**Comment by NolanHzy** [comment]
{
///最大支持几个网页
"MaxTab": "4",
//网站标题
"Title": "京东签到获取小饼干",
//网站公告
"Announcement": "此工具仅限内部使用，为了您的财产安全，请关闭京东免密支付。",
///多青龙配置
"Config": [
{
//序号必须从1开始
"QLkey": 1,
//服务器名称
"QLName": "重庆电信-动态IP",
//青龙url
"QLurl": "http://16:5700",
//青龙2,9 OpenApi Client ID
"QL_CLIENTID": "o8ep",
//青龙2,9 OpenApi Client Secret
"QL_SECRET": "EawwEpY",
//青龙面包最大ck容量
"QL_CAPACITY": 50,
//消息推送二维码
"QRurl":""
},
{
//序号必须从1开始
"QLkey": 2,
//服务器名称
"QLName": "上海良心云-固定IP",
//青龙url
"QLurl": "http://16:5700",
//青龙2,9 OpenApi Client ID
"QL_CLIENTID": "o8ep",
//青龙2,9 OpenApi Client Secret
"QL_SECRET": "EawwEpY",
//青龙面包最大ck容量
"QL_CAPACITY": 50,
//消息推送二维码
"QRurl":""
}
]
}
